server:
  port: 83

spring:
  application:
    name: nacos-order-consumer
    #spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://nacos-payment-provider