#配置zookeeper
server:
  port: 8004
spring:
  application:
    name: cloud-provider-service
  cloud:
    zookeeper:
      connect-string: 192.168.49.129:2181
      discovery:
        instance-host: localhost

